_frozen_importlib:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
Traceback (most recent call last):
  File "mini_test.py", line 159, in <module>
    factorizer.factorize(report=args.report, max_iteration=max_iterations, fixed_covariance=fixed_covariance, to_report=[0, 5, 10, 20,  50, 100, 200])
  File "/cluster/home/mnguye16/SSVI/SSVI-TF/SSVI/SSVI_TF_interface.py", line 116, in factorize
    self.update_natural_param_batch(dim, col)
  File "/cluster/home/mnguye16/SSVI/SSVI-TF/SSVI/SSVI_TF_interface.py", line 189, in update_natural_param_batch
    S_next   = self.update_cov_param(dim, i, m, S, di, Di)
  File "/cluster/home/mnguye16/SSVI/SSVI-TF/SSVI/SSVI_TF_interface.py", line 304, in update_cov_param
    S_next = inv((1 - covStep) * inv(S) + np.multiply(covStep, covGrad))
  File "/cluster/home/mnguye16/SSVI/SSVI-TF/venv/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 532, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/cluster/home/mnguye16/SSVI/SSVI-TF/venv/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix
